"""Static city presets for Indian real-estate."""

CITY_PRESETS = [
    {
        "city": "Bengaluru",
        "avg_price_per_sqft": 9500,
        "expected_appreciation": 7.5,
        "rental_yield": 3.2,
        "avg_monthly_rent_2bhk": 32000,
        "rent_increase": 8.0,
        "notes": "Tech-driven; Whitefield, Electronic City, Sarjapur strong.",
    },
    {
        "city": "Mumbai",
        "avg_price_per_sqft": 24000,
        "expected_appreciation": 5.5,
        "rental_yield": 2.8,
        "avg_monthly_rent_2bhk": 58000,
        "rent_increase": 6.0,
        "notes": "High ticket, low yield. Navi Mumbai better for yield.",
    },
    {
        "city": "Delhi NCR",
        "avg_price_per_sqft": 10500,
        "expected_appreciation": 6.5,
        "rental_yield": 2.9,
        "avg_monthly_rent_2bhk": 38000,
        "rent_increase": 7.0,
        "notes": "Gurgaon/Noida outperform Delhi proper on appreciation.",
    },
    {
        "city": "Hyderabad",
        "avg_price_per_sqft": 7800,
        "expected_appreciation": 8.5,
        "rental_yield": 3.6,
        "avg_monthly_rent_2bhk": 27000,
        "rent_increase": 8.0,
        "notes": "Gachibowli/Kokapet leading; strong infra spend.",
    },
    {
        "city": "Pune",
        "avg_price_per_sqft": 8800,
        "expected_appreciation": 7.0,
        "rental_yield": 3.3,
        "avg_monthly_rent_2bhk": 30000,
        "rent_increase": 7.5,
        "notes": "IT corridors Hinjawadi/Kharadi; stable rental demand.",
    },
    {
        "city": "Chennai",
        "avg_price_per_sqft": 7500,
        "expected_appreciation": 6.0,
        "rental_yield": 3.1,
        "avg_monthly_rent_2bhk": 26000,
        "rent_increase": 6.5,
        "notes": "OMR/Porur stable; floods a recurring variable.",
    },
    {
        "city": "Kolkata",
        "avg_price_per_sqft": 6200,
        "expected_appreciation": 4.5,
        "rental_yield": 3.4,
        "avg_monthly_rent_2bhk": 22000,
        "rent_increase": 5.5,
        "notes": "New Town/Rajarhat pockets of growth.",
    },
    {
        "city": "Ahmedabad",
        "avg_price_per_sqft": 5800,
        "expected_appreciation": 6.5,
        "rental_yield": 3.0,
        "avg_monthly_rent_2bhk": 20000,
        "rent_increase": 6.0,
        "notes": "SG Highway corridor strong; low entry ticket.",
    },
]
